# Generated by Django 3.0.2 on 2020-02-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DAY')),
            ],
        ),
        migrations.CreateModel(
            name='ICC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DAY')),
            ],
        ),
        migrations.CreateModel(
            name='HAWAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DAY')),
            ],
        ),
        migrations.CreateModel(
            name='FCLT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DAY')),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DAY')),
            ],
        ),
        migrations.CreateModel(
            name='EAST2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DAY')),
            ],
        ),
        migrations.CreateModel(
            name='EAST1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DAY')),
            ],
        ),
    ]
