# Generated by Django 3.0.2 on 2020-02-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200202_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='time',
            new_name='day',
        ),
    ]
