# Generated by Django 3.0.2 on 2020-02-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200202_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='east1',
            name='menu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='east2',
            name='menu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='menu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='fclt',
            name='menu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='hawam',
            name='menu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='icc',
            name='menu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='west',
            name='menu',
            field=models.TextField(default='', null=True),
        ),
    ]
